### ISSUE TITLE
spid-compliant-certificates integration

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-sp-test#12]
https://github.com/italia/spid-compliant-certificates

have:
- https://github.com/italia/spid-compliant-certificates/blob/master/validator/validator.py importable as python package
- a new test category with a brand new CLI parameter to deal with

**Comment by psmiraglia** [comment]
I'm working on Python native solution to generate and validate X509 certificates according to Avviso SPID n29 v3 (https://github.com/psmiraglia/spid-compliant-certificates/tree/wip/python/python). The package, **still under active development**, already provides importable test cases.

**install the package**

```
$ git clone https://github.com/psmiraglia/spid-compliant-certificates.git
$ cd spid-compliant-certificates
$ git checkout --track origin/wip/python
$ cd python
$ pip install .
```

**use the test cases from the cmd line**

```
$ export CERT_FILE=/path/to/your/cert.pem 
$ python3 -m unittest -v spid_compliant_certificates.validator.test_cases.TestPublicSector
$ python3 -m unittest -v spid_compliant_certificates.validator.test_cases.TestPrivateSector
```

**use the test cases within your code**

```
from spid_compliant_certificates.validator.test_cases import TestPublicSector, TestPrivateSector
```

**Comment by peppelinux** [comment]
This can be useful to have an integrable json report in the one produced by spid-sp-test 
https://github.com/italia/spid-compliant-certificates-python/issues/21

**Comment by walter-arrighetti** [comment]
Thanks @psmiraglia  In addition to [Avviso SPID №19](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati_0.pdf)/2020, it would be useful to CI it in order to validate also against:

- [Avviso SPID №19](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n19v4-regole_tecniche_aggregatori.pdf)/2020  - AgID  (for SP aggregators)
- [Manuale tecnico per i fornitori di Servizi Pubblici e Privati](https://docs.italia.it/italia/cie/cie-manuale-tecnico-docs/it/master/index.html) della CIE

**Comment by peppelinux** [comment]
Done https://github.com/italia/spid-sp-test/releases/tag/v1.1.0
