### ISSUE TITLE
The Location attribute MUST be a valid HTTPS url without port

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-sp-test#55]
here:

https://github.com/italia/spid-sp-test/blob/f1989f9f9215b0e577e3f699caf04d208a82679b/src/spid_sp_test/metadata.py#L128

avoid any custom tcp port in the validation regexp

**Comment by mauromol** [comment]
Why not custom ports? Where does the SPID specification requires the use of port 443?

**Comment by peppelinux** [comment]
Let's assume that an Enterprise firewall would block foreign connection to not standard ports, on the Edge. It's something frequent.

This would be checked only if production flag Is on, do no worries for development servers.

Hope that you agree this, otherwise I'll reopen it

**Comment by mauromol** [comment]
Actually, I was wondering why custom ports should be forbidden in production. Obviously, if I am so silly to block the port I want to use in production (or to misconfigure the necessary port-forwarding rule), my SP won't work, but hey... if I shutdown my SP it won't work either :-D

So, unless the SPID specification explicitly denies to use custom ports (but why?!?!?), I would not expect spid-sp-test to prevent me from doing that, even when enabling the production flag...

The only requirement I currently find in SPID specification is to use TLS, and hence HTTPS, so having the --production flag check that the protocol is HTTPS rather than plain HTTP is reasonable. But the port should be customizable, IMHO...
However, IPs and standard ports are precious resources and depending on the deploying environment port 80 and 443 may be unavailable: SP URLs are not something that the end user should remember or even bookmark, therefore the use of custom ports does not hurt in any way. So unless there's a strong argument to mandate their use I think SPs should be given the ability to use alternative ports.

IMHO, as always...
